load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")
load("//:CPPVARIABLES.bzl", "DDS_CPPOPTS", "DDS_LINKOPTS", "DDS_LOCAL_DEFINES")

UTILITIES_CPPOPTS = DDS_CPPOPTS + select({
    "//:build_windows": [],
    "//:build_wasm": [],
    "//:debug_build_windows": [],
    "//conditions:default": [
        "-Wno-deprecated-declarations",
    ],
})

UTILITIES_LOCAL_DEFINES = DDS_LOCAL_DEFINES + select({
    "//:build_windows": ["_CRT_SECURE_NO_WARNINGS"],
    "//:debug_build_windows": ["_CRT_SECURE_NO_WARNINGS"],
    "//conditions:default": [],
})

cc_library(
    name = "dd_table_for_deal_lib",
    srcs = ["src/dd_table_for_deal/dd_table_for_deal_lib.cpp"],
    hdrs = ["src/dd_table_for_deal/dd_table_for_deal.hpp"],
    includes = ["src/dd_table_for_deal"],
    copts = UTILITIES_CPPOPTS,
    local_defines = UTILITIES_LOCAL_DEFINES,
    deps = [
        "//library/src/api:api_definitions",
    ],
)

cc_binary(
    name = "dd_table_for_deal",
    srcs = ["src/dd_table_for_deal/dd_table_for_deal.cpp"],
    copts = UTILITIES_CPPOPTS,
    linkopts = DDS_LINKOPTS,
    local_defines = UTILITIES_LOCAL_DEFINES,
    deps = [
        ":dd_table_for_deal_lib",
        "//examples:hands",
        "//library/src:dds",
        "//library/src/api:api_definitions",
    ],
)

cc_test(
    name = "dd_table_for_deal_test",
    size = "small",
    srcs = ["tests/dd_table_for_deal_test.cpp"],
    copts = UTILITIES_CPPOPTS,
    local_defines = UTILITIES_LOCAL_DEFINES,
    deps = [
        ":dd_table_for_deal_lib",
        "//library/src/api:api_definitions",
        "@googletest//:gtest_main",
    ],
)
