load("//:CPPVARIABLES.bzl", "DDS_CPPOPTS")
load("@pybind11_bazel//:build_defs.bzl", "pybind_extension")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

pybind_extension(
    name = "dds3_ext",
    srcs = ["src/bindings.cpp"],
    copts = DDS_CPPOPTS,
    deps = [
        "//library/src:dds",
    ],
    visibility = ["//visibility:public"],
)

py_library(
    name = "dds3_lib",
    srcs = ["dds3/__init__.py"],
    data = [":dds3_ext"],
    imports = ["."],
    visibility = ["//visibility:public"],
)

py_test(
    name = "python_interface_smoke_test",
    main = "tests/test_import.py",
    srcs = ["tests/test_import.py"],
    deps = [":dds3_lib"],
)
