load("@emsdk//emscripten_toolchain:wasm_rules.bzl", "wasm_cc_binary")

wasm_cc_binary(
    name = "solve_board_wasm",
    cc_target = "//examples:solve_board",
    outputs = [
        "solve_board.js",
        "solve_board.wasm",
    ],
)

wasm_cc_binary(
    name = "analyse_play_bin_wasm",
    cc_target = "//examples:AnalysePlayBin",
    outputs = [
        "AnalysePlayBin.js",
        "AnalysePlayBin.wasm",
    ],
)

wasm_cc_binary(
    name = "calc_dd_table_pbn_wasm",
    cc_target = "//examples:calc_dd_table_pbn",
    outputs = [
        "calc_dd_table_pbn.js",
        "calc_dd_table_pbn.wasm",
    ],
)

filegroup(
    name = "all_examples_wasm",
    srcs = [
        ":analyse_play_bin_wasm",
        ":calc_dd_table_pbn_wasm",
        ":solve_board_wasm",
    ],
    visibility = ["//visibility:public"],
)
