name: CI – macOS

on:
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Bazelisk (the recommended Bazel launcher)
      - name: Install Bazelisk
        run: brew install bazelisk

      # Install Doxygen, to generate documentation
      - name: Install Doxygen
        run: brew install doxygen

      # Install clang 20
      - name: Install Clang
        run: brew install llvm@20

      # Softlink llvm@20 to llvm
      - name: Softlink Clang
        run: ln -s /opt/homebrew/opt/llvm@20 /opt/homebrew/opt/llvm

      # Build Python extension
      - name: Build Python extension
        run: bazelisk build //python:_dds3

      # Build everything
      - name: Build all targets
        run: bazelisk build //...

      # Run Python smoke test
      - name: Run Python smoke test
        run: bazelisk test //python:python_interface_smoke_test

      # Run Python pytest suite
      - name: Run Python pytest suite
        run: |
          bazelisk run @python_3_14//:python3 -- -m pip install --upgrade pip pytest
          export DDS_PYTHON_EXT_DIR="$(bazelisk info bazel-bin)/python"
          export PYTHONPATH="python:${DDS_PYTHON_EXT_DIR}"
          bazelisk run @python_3_14//:python3 -- -m pytest python/tests/ -v

      # Run all tests
      - name: Run all tests
        run: bazelisk test //...
