#!/usr/bin/env python3
"""Emit dds_mvp_wasm_bin.js with base64-encoded wasm for file:// and HTTP."""
from __future__ import annotations

import base64
import sys
from pathlib import Path

HEADER = """\
// Generated by web/gen_wasm_bin_js.py — do not edit.
"use strict";

function ddsMvpWasmBytes() {
    const bin = atob(DDS_MVP_WASM_BASE64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) {
        out[i] = bin.charCodeAt(i);
    }
    return out;
}
"""


def usage() -> None:
    name = Path(sys.argv[0]).name
    print(f"usage: {name} WASM_FILE OUTPUT_JS", file=sys.stderr)


def make_bin_js(wasm_bytes: bytes) -> str:
    """Return the contents of dds_mvp_wasm_bin.js for the given wasm module."""
    b64 = base64.b64encode(wasm_bytes).decode("ascii")
    lines = [b64[i : i + 76] for i in range(0, len(b64), 76)]
    body = 'const DDS_MVP_WASM_BASE64 =\n    "' + '" +\n    "'.join(lines) + '";\n\n'
    return HEADER + body


def main() -> int:
    if len(sys.argv) != 3:
        usage()
        return 2

    wasm_path = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    out_path.write_text(make_bin_js(wasm_path.read_bytes()), encoding="utf-8")
    print(f"wrote {out_path} ({wasm_path.stat().st_size} byte wasm)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
