#!/usr/bin/env python3
"""Patch the single isFileURI line in Emscripten output.

Do not use global substitution on SINGLE_FILE builds: the embedded wasm
bytes can contain arbitrary text that would corrupt the module.

The Emscripten line we patch is generated by rules_emscripten / emsdk. When
upgrading `bazel_dep(name = "emsdk", ...)` in MODULE.bazel, rebuild
`//web:dds_web_wasm` and run this script; if the regex no longer matches,
update UNPATCHED_IS_FILE_URI below and document the new version in
docs/wasm_build.md.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Keep in sync with bazel_dep(name = "emsdk", version = "...") in MODULE.bazel.
EXPECTED_EMSDK_BAZEL_DEP_VERSION = "5.0.7"

# Emscripten 5.x (emsdk 5.0.7): var isFileURI = filename => filename.startsWith("file://");
# Older emsdk also emitted parentheses around the parameter.
UNPATCHED_IS_FILE_URI = re.compile(
    r"var\s+isFileURI\s*=\s*(?:\(\s*)?(\w+)(?:\s*\))?\s*=>\s*"
    r"\1\.startsWith\(\s*['\"]file://['\"]\s*\)\s*;",
)

# Already patched by a previous run of this script.
PATCHED_IS_FILE_URI = re.compile(
    r"var\s+isFileURI\s*=\s*(?:\(\s*)?(\w+)(?:\s*\))?\s*=>\s*"
    r"\(\s*typeof\s+\1\s*===\s*['\"]string['\"]",
)


def patched_line(param: str) -> str:
    return (
        f"var isFileURI = ({param}) => "
        f"(typeof {param} === 'string' ? {param} : ({param} && {param}.href) || '')"
        f".startsWith('file://');"
    )


def usage() -> None:
    name = Path(sys.argv[0]).name
    print(f"usage: {name} EMSCRIPTEN_JS", file=sys.stderr)


def patch_text(text: str) -> tuple[str, int]:
    """Return patched text and an exit code (0 success, 1 error)."""
    if PATCHED_IS_FILE_URI.search(text):
        return text, 0

    matches = list(UNPATCHED_IS_FILE_URI.finditer(text))
    if not matches:
        print(
            "patch_web_wasm: isFileURI declaration not found "
            f"(expected Emscripten output from emsdk BCR {EXPECTED_EMSDK_BAZEL_DEP_VERSION}).\n"
            "After upgrading emsdk, rebuild //web:dds_web_wasm and update "
            "UNPATCHED_IS_FILE_URI in web/patch_web_wasm.py if the generator changed.",
            file=sys.stderr,
        )
        return text, 1
    if len(matches) != 1:
        print(
            f"patch_web_wasm: expected 1 isFileURI declaration, found {len(matches)}",
            file=sys.stderr,
        )
        return text, 1

    match = matches[0]
    param = match.group(1)
    replacement = patched_line(param)
    updated = text[: match.start()] + replacement + text[match.end() :]
    return updated, 0


def main() -> int:
    if len(sys.argv) != 2:
        usage()
        return 2

    path = Path(sys.argv[1])
    text = path.read_text(encoding="utf-8")
    updated, code = patch_text(text)
    if code != 0:
        return code
    if updated != text:
        path.write_text(updated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
